board/urls.py
from django.urls import path
from . import views



urlpatterns = [
    # review url
    path('', views.IndexView.as_view(), name='index'),
    path('search/', views.SearchView.as_view(), name='search'),
    path(
        "reviews/<int:review_id>/",
        views.ReviewDetailView.as_view(),
        name='review-detail',
    ),
    path("reviews/new/", views.ReviewCreateView.as_view(), name="review-create"),
    path(
        "reviews/<int:review_id>/edit/",
        views.ReviewUpdateView.as_view(),
        name="review-update",
    ),
    path(
        "reviews/<int:review_id>/delete/",
        views.ReviewDeleteView.as_view(),
        name="review-delete",
    ),
    # profile urls 
    path("users/<int:user_id>/", views.ProfileView.as_view(), name="profile"),
    path(
        "users/<int:user_id>/reviews/", 
        views.UserReviewListView.as_view(), 
        name="user-review-list"
        ),
    path("set-profile/", views.ProfileSetView.as_view(), name="profile-set"),
    path("edit-profile/", views.ProfileUpdateView.as_view(), name="profile-update"),


    # comment
    path(
        'reviews/<int:review_id>/comments/create/',
        views.CommentCreateView.as_view(),
        name='comment-create',
    ),
    path(
        'comments/<int:comment_id>/edit/', 
        views.CommentUpdateView.as_view(), 
        name='comment-update'
    ),
    path(
        'comments/<int:comment_id>/delete/', 
        views.CommentDeleteView.as_view(), 
        name='comment-delete'
    ),
    path(
        'like/<int:content_type_id>/<int:object_id>/',
        views.ProcessLikeView.as_view(),
        name='process-like'
    ),
]

chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'

urlpatterns = [
    path("", views.index, name="index"),
    path("<str:room_name>/", views.room, name="room"),
]

mbtichatting/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from board.views import CustomPasswordChangeView

urlpatterns = [
    # admin
    path('admin/', admin.site.urls),
    # board
    path('', include('board.urls')),
    # allauth
    path(
        "email-confirmation-required/",
        TemplateView.as_view(template_name="account/email_confirmation_required.html"),
        name="account_email_confirmation_required"
    ),
    path(
        "email-confirmation-done/",
        TemplateView.as_view(template_name="board/email_confirmation_done.html"),
        name="account_email_confirmation_done"
    ),
    path(
        'password/change/', 
        CustomPasswordChangeView.as_view(), 
        name="account_password_change",),
    path('', include('allauth.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/models.py
from typing import Generic
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from .validators import validate_no_special_characters, validate_email
# from .validators import validate_no_special_characters, validate_restaurant_link
# Create your models here.

class User(AbstractUser):
    mail = models.CharField(max_length=60, unique=True, null=True, validators=[validate_email], error_messages ={'unique': '이미 사용중인 이메일입니다.'})
    nickname = models.CharField(
        max_length=15, 
        unique=True, 
        null=True,
        validators=[validate_no_special_characters],
        error_messages ={'unique': '이미 사용중인 닉네임입니다.'},
    )
    mbti = models.CharField(max_length=60, blank=True)
    profile_img = models.ImageField(null=True)
    profile_pic = models.ImageField(default="default_profile_pic.jpg", upload_to="profile_pics")

    intro = models.CharField(max_length=60, blank=True)

    following = models.ManyToManyField(
        'self', 
        symmetrical=False, 
        blank=True, 
        related_name='followers'
    )
    
    def __str__(self):
        return self.email


class Review(models.Model):
    title = models.CharField(max_length=30)
    # restaurant_name = models.CharField(max_length=20)
    # restaurant_link = models.URLField(validators=[validate_restaurant_link])


    # RATING_CHOICES = [
    #     (1,"★"),
    #     (2,"★★"),
    #     (3,"★★★"),
    #     (4,"★★★★"),
    #     (5,"★★★★★"),
    # ]
    # rating = models.IntegerField(choices=RATING_CHOICES, default=None)

    image1 = models.ImageField(upload_to="review_pics", blank=True)
    image2 = models.ImageField(upload_to="review_pics", blank=True)
    image3 = models.ImageField(upload_to="review_pics", blank=True)
    content = models.TextField()
    dt_created = models.DateTimeField(auto_now_add=True)
    dt_updated = models.DateTimeField(auto_now=True)

    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reviews')

    likes = GenericRelation('Like', related_query_name='review')

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-dt_created']

class Comment(models.Model):
    content = models.TextField(max_length=500, blank=False)

    dt_created = models.DateTimeField(auto_now_add=True)

    dt_updated = models.DateTimeField(auto_now=True)

    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')

    review = models.ForeignKey(Review, on_delete=models.CASCADE, related_name='comments')

    likes = GenericRelation('Like', related_query_name='comment')

    def __str__(self):
        return self.content[:30]

class Like(models.Model):
    dt_created = models.DateTimeField(auto_now_add=True)

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='likes')

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)

    object_id = models.PositiveBigIntegerField()

    liked_object = GenericForeignKey()

    def __str__(self):
        return f"({self.user}, {self.liked_object})"

board/forms.py
from django import forms
from .models import User, Review, Comment

class SignupForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["mail", "nickname",]

    def signup(self, request, user):
        user.mail = self.cleaned_data["mail"]
        user.nickname = self.cleaned_data["nickname"]
        user.save()

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = [
            "title",
            # "restaurant_name",
            # "restaurant_link",
            # "rating",
            "image1",
            "image2",
            "image3",
            "content",
        ]
        # widgets = {
        #     "rating": forms.RadioSelect,
        # }

class ProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            # "nickname",
            "profile_pic",
            "intro",
            "mbti",
        ]
        widgets = {
            # "intro" : forms.Textarea,
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            'content', 
        ]
        widgets = {
            'content' : forms.Textarea,
        }

board/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views.generic import (
    View,
    ListView, 
    DetailView, 
    CreateView, 
    UpdateView,
    DeleteView,
)
from django.contrib.contenttypes.models import ContentType
from django.db.models import Q
from braces.views import LoginRequiredMixin
from allauth.account.views import PasswordChangeView

from .mixins import LoginAndVerificationRequiredMixin, LoginAndOwnershipRequiredMixin
from .models import Review, User, Comment, Like
from .forms import ReviewForm, ProfileForm, CommentForm

# Create your views here.

class IndexView(ListView):
    model = Review
    template_name = "board/index.html"
    context_object_name = "reviews"
    paginate_by = 4
    ordering = ["-dt_created"]


class SearchView(ListView):
    model = Review
    context_object_name = 'search_results'
    template_name = 'board/search_results.html'
    paginate_by = 8

    def get_queryset(self):
        query = self.request.GET.get('query', '')
        return Review.objects.filter(
            Q(title__icontains=query)
            | Q(content__icontains=query)
        )
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = self.request.GET.get('query', '')
        return context

class ReviewDetailView(DetailView):
    model = Review
    template_name = "board/review_detail.html"
    pk_url_kwarg = "review_id"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CommentForm()
        context['review_ctype_id'] = ContentType.objects.get(model='review').id
        context['comment_ctype_id'] = ContentType.objects.get(model='comment').id

        user = self.request.user
        if user.is_authenticated:
            review = self.object
            context['likes_review'] = Like.objects.filter(user=user, review=review).exists()
            context['liked_comments'] = Comment.objects.filter(review=review).filter(likes__user=user)
        return context

class ReviewCreateView(LoginAndVerificationRequiredMixin, CreateView):
    model = Review
    form_class = ReviewForm
    template_name = "board/review_form.html"



    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("review-detail", kwargs={"review_id": self.object.id})

        

class ReviewUpdateView(LoginAndOwnershipRequiredMixin, UpdateView):
    model = Review
    form_class = ReviewForm
    template_name = "board/review_form.html"
    pk_url_kwarg = "review_id"


    def get_success_url(self):
        return reverse("review-detail", kwargs={"review_id": self.object.id})



class ReviewDeleteView(LoginAndOwnershipRequiredMixin, DeleteView):
    model = Review
    template_name = "board/review_confirm_delete.html"
    pk_url_kwarg = "review_id"

    def get_success_url(self):
        return reverse("index")


class CommentCreateView(LoginAndVerificationRequiredMixin, CreateView):
    http_method_names = ['post']
    model = Comment
    form_class = CommentForm


    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.review = Review.objects.get(id=self.kwargs.get('review_id'))
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('review-detail', kwargs={'review_id': self.kwargs.get('review_id')})

class CommentUpdateView(LoginAndOwnershipRequiredMixin, UpdateView):
    model = Comment
    form_class = CommentForm
    template_name = 'board/comment_update_form.html'
    pk_url_kwarg = 'comment_id'

    def get_success_url(self):
        return reverse('review-detail', kwargs={'review_id': self.object.review.id})


class CommentDeleteView(LoginAndOwnershipRequiredMixin, DeleteView):
    model = Comment
    template_name = 'board/comment_confirm_delete.html'
    pk_url_kwarg = 'comment_id'

    def get_success_url(self):
        return reverse('review-detail', kwargs={'review_id': self.object.review.id})

class ProcessLikeView(LoginAndVerificationRequiredMixin, View):
    http_method_names= ['post']

    def post(self, request, *args, **kwargs):
        like, created = Like.objects.get_or_create(
            user=self.request.user,
            content_type_id=self.kwargs.get('content_type_id'),
            object_id=self.kwargs.get('object_id')
        )
        if not created:
            like.delete()
        return redirect(self.request.META['HTTP_REFERER'])

class ProfileView(DetailView):
    model = User
    template_name = "board/profile.html"
    pk_url_kwarg = "user_id"
    context_object_name = "profile_user"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_id = self.kwargs.get("user_id")
        context["user_reviews"] = Review.objects.filter(author__id=user_id).order_by("-dt_created")[:4]
        return context

class UserReviewListView(ListView):
    model = Review
    template_name = "board/user_review_list.html"
    context_object_name = "user_reviews"
    paginate_by = 4

    def get_queryset(self):
        user_id = self.kwargs.get("user_id")
        return Review.objects.filter(author__id=user_id).order_by("dt_created")
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["profile_user"] = get_object_or_404(User, id=self.kwargs.get("user_id"))
        return context

class ProfileSetView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = ProfileForm
    template_name = "board/profile_set_form.html"

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self):
        return reverse("index")

class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = ProfileForm
    template_name = "board/profile_update_form.html"

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self):
        return reverse("profile", kwargs=({"user_id": self.request.user.id}))

class CustomPasswordChangeView(LoginRequiredMixin, PasswordChangeView):
    def get_success_url(self):
        return reverse("proile", kwargs=({"user_id": self.request.user.id}))

board/templates/board/comment_confirm_delete.html
{% extends "board_base/base_with_navbar.html" %}

{% block title %}댓글 삭제 {% endblock title %}

{% block content %}
<main class="site-body">
  <form class="cp-dialog confirm-delete" method="post">
    {% csrf_token %}
    <span class="content">정말 댓글을 삭제하시겠습니까?</span>
    <button class="cp-button warn" type="submit">삭제</button>
    <a class="cp-button secondary" href="{% url 'review-detail' comment.review.id %}">취소</a>
  </form>
</main>
{% endblock content %}

board/templates/board/comment_update_form.html
{% extends "board_base/base_with_navbar.html" %}

{% load widget_tweaks %}

{% block title %}댓글 수정 {% endblock title %}

{% block content %}
<main class="site-body">
  <form class="comment-update-form" method="post">
    {% csrf_token %}
    {{ form.content|attr:"placeholder:댓글 내용을 입력해주세요."|add_class:"cp-input" }}
    <div class="buttons">
      <button class="cp-button small" type="submit">완료</button>
      <a class="cp-button small secondary" href="{% url 'review-detail' comment.review.id %}">취소</a>
    </div>
  </form>
</main>
{% endblock content %}

board/templates/board/email_confirmation_done.html
이메일 인증이 완료되었습니다. 
{% if user.is_authenticated%} 
    <a href="{% url 'index' %}">홈으로 이동</a>

{% else %}
<a href="{% url 'account_login' %}">로그인 하기</a>
{% endif %}

board/templates/board/index.html
{% extends "board_base/base_with_navbar.html" %}

{% block content %}
<main class="site-body">
  <div class="main-header">
    <div class="content" style="margin-top: 70px;">
      <div class="fg"></div>
      <h1>MBTICHATTING</h1>
    </div>
  </div>

  <div class="content-list max-content-width">
    <div class="header">
      <h2>게시글</h2>
      <div class="header-search">
        <form class="search-form" action="{% url 'search' %}" method="get">
          <input class="search-input" name="query" type="text" placeholder="게시글을 검색해보세요" required>
          <button class="cp-button search-button" type="submit">검색</button>
        </form>
      </div>
      <a class="cp-ic-button circle newreview" href="{% url 'review-create' %}">글 작성</a>
    </div>

      <div class="contents">
      {% for review in reviews %}
        <a href="{% url 'review-detail' review.id %}">
            <section class="cp-card content">
              {% if review.image1 %}
              <div class="thumb" style="background-image: url('{{ review.image1.url }}');"></div>
              {% endif %}
              <div class="body">
                <span class="cp-chip green">{{ review.restaurant_name }}</span>
                <h2 class="title">{{ review.title }}</h2>
                <date class="date">{{ review.dt_created|date:"Y년 n월 j일" }}</date>
                <div class="metadata">
                  {% comment %} <div class="review-rating">
                    <span class="cp-stars">
                      {% for i in ""|ljust:review.rating %}★{% endfor%}
                    </span>
                  </div> {% endcomment %}
                  <div class="review-author">
                    <div class="cp-avatar" style="background-image: url('{{ review.author.profile_pic.url }}')"></div>
                    <span>{{ review.author.nickname }}</span>
                  </div>
                </div>
              </div>
            </section>
          </a>
      {% empty %}
        <p class="empty">아직 게시글이 없어요</p>
      {% endfor %}
      </div>

      {% if is_paginated %}
        <footer>
          <ul class="pagination">
            {% if page_obj.has_previous %}
              <li><a href="?page=1">처음</a></li>
              <li><a href="?page={{ page_obj.previous_page_number }}">이전</a></li>
            {% endif %}

            {% for num in page_obj.paginator.page_range %}
              {% if page_obj.number == num %}
                <li class="current">{{ num }}</li>
              {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <li><a href="?page={{ num }}">{{ num }}</a></li>
              {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
              <li><a href="?page={{ page_obj.next_page_number }}">다음</a></li>
              <li><a href="?page={{ page_obj.paginator.num_pages }}">마지막</a></li>
            {% endif %}
          </ul>
        </footer>
      {% endif %}
    </article>
  </div>
</main>
{% endblock content %}

board/templates/board/profile.html
{% extends "board_base/base_with_navbar.html" %} {% load static %} {% block title %}{{ profile_user.nickname }} {% endblock title %} {% block content %}
<main class="site-body">
  <div class="profile-header">
    <div class="content max-content-width">
      <div
        class="cp-avatar large profile-pic"
        style="background-image: url('{{ profile_user.profile_pic.url }}')"
      ></div>
      <div class="info">
        <h1 class="username">{{ profile_user.nickname }}</h1>
        {% if profile_user == user%} 
          <a class="edit" href="{% url 'profile-update' %}">
            <img class="cp-icon small" src="{% static 'board/icons/ic-pen.svg' %}" alt="Pen Icon">
            프로필 수정
          </a>
          &#183;
          <a class="edit" href="{% url 'account_change_password' %}">
            비밀번호 변경
          </a>
        {% endif %}
        {% if profile_user.mbti %}
        <div>
          <p class="cp-chip intro">{{ profile_user.mbti }}</p>
        </div>
        {% endif %}
        {% if profile_user.intro %}
          <div>
            <p class="cp-chip intro">{{ profile_user.intro }}</p>
          </div>
        {% endif %}
      </div>
    </div>
  </div>

  <div class="content-list max-content-width">
    <div class="header">
      <h2>{{ profile_user.nickname }}님의 게시글</h2>
      {% if user_reviews %}
        <a class="cp-ic-button after circle morereview" href="{% url 'user-review-list' profile_user.id %}">
          게시글 전체보기
        </a>
      {% endif %}
    </div>

    <div class="contents">
      {% for review in user_reviews %}
      <a href="{% url 'review-detail' review.id %}">
        <div class="cp-card content">
          {% if review.image1%}
            <div class="thumb" style="background-image: url('{{ review.image1.url }}');">
          {% endif%}
          </div>
          <div class="body">
            <span class="cp-chip green">{{ review.restaurant_name }}</span>
            <h2 class="title">{{ review.title }}</h2>
            <date class="date">{{ review.dt_created|date:"Y년 n월 j일" }}</date>
            <div class="metadata">
              {% comment %} <div class="review-rating">
                <span class="cp-stars">
                  {% for i in ""|ljust:review.rating %}★{% endfor %}
                </span>
              </div> {% endcomment %}
              <div class="review-author">
                <div
                  class="cp-avatar"
                  style="background-image: url('{{ review.author.profile_pic.url }}')"
                ></div>
                <span>{{ review.author.nickname }}</span>
              </div>
            </div>
          </div>
        </div>
      </a>
      {% empty %}
      <p class="empty">아직 게시글이 없어요 :(</p>
      {% endfor %}
    </div>
  </div>
</main>
{% endblock content %}

board/templates/board/profile_set_form.html
{% extends "board_base/base.html" %}

{% load static %}
{% load widget_tweaks %}

{% block title %}환영합니다! | MBCHATTING{% endblock title %}

{% block content %}
<div class="account-background">
  <main class="profile-form">
    {% comment %} <div class="logo">
      <img class="logo" src="{% static 'board/assets/logo.jpg' %}" alt="board Logo">
    </div> {% endcomment %}
    <p class="welcome-message">
      환영합니다! <strong>프로필</strong>을 작성해주세요
    </p>
    <form method="post" enctype="multipart/form-data" autocomplete="off">
      {% csrf_token %}
      <div class="profile">
        <div class="profile-pic cp-avatar large" style="background-image: url('{{ user.profile_pic.url }}')"></div>
        <div class="file">
          {{ form.profile_pic }}
        </div>
      </div>
      <div class="nickname">
        {{ form.nickname|add_class:"cp-input"|add_error_class:"error"|attr:"placeholder:닉네임" }}
        {% for error in form.nickname.errors %}
          <div class="error-message">{{ error }}</div>
        {% endfor %}
      </div>
      <div>
        {{ form.mbti|add_class:"cp-input"|attr:"placeholder:mbti"|add_error_class:"error"}}
        {% for error in form.mbti.errors %}
          <div class="error-message">{{ error }}</div>
        {% endfor%}
      </div> 
      <div>
        <li><a href="https://www.16personalities.com/ko">mbti 확인</a></li>
      </div>
      <div class="content">
        {{ form.intro|add_class:"cp-input"|add_error_class:"error"|attr:"placeholder:자신을 소개해 주세요!" }}
        {% for error in form.intro.errors %}
          <div class="error-message">{{ error }}</div>
        {% endfor %}
      </div>
      <div class="buttons">
        <button class="cp-button" type="submit">완료</button>
      </div>
    </form>
  </main>
</div>
{% endblock content %}
  

board/templates/board/profile_update_form.html
{% extends "board_base/base_with_header.html" %}

{% load widget_tweaks %}

{% block title %}프로필 수정 | MBCHATTING{% endblock title %}

{% block content %}
<main class="profile-form">
  <form method="post" enctype="multipart/form-data" autocomplete="off">
    {% csrf_token %}
    <div class="profile">
      <div class="profile-pic cp-avatar large" style="background-image: url('{{ user.profile_pic.url }}')"></div>
      <div class="file">
        {{ form.profile_pic }}
      </div>
    </div>
    <div class="nickname">
      {{ form.nickname|add_class:"cp-input"|add_error_class:"error"|attr:"placeholder:닉네임" }}
      {% for error in form.nickname.errors %}
        <div class="error-message">{{ error }}</div>
      {% endfor %}
    </div>
    <div>
      {{ form.mbti|add_class:"cp-input"|attr:"placeholder:mbti"|add_error_class:"error"}}
      {% for error in form.mbti.errors %}
        <div class="error-message">{{ error }}</div>
      {% endfor%}
    </div> 
    <div class="content">
      {{ form.intro|add_class:"cp-input"|add_error_class:"error"|attr:"placeholder:자신을 소개해 주세요!" }}
      {% for error in form.intro.errors %}
        <div class="error-message">{{ error }}</div>
      {% endfor %}
    </div>
    <div class="buttons">
      <a class="cp-button secondary cancel" href="{% url 'profile' user.id %}">취소</a>
      <button class="cp-button" type="submit">완료</button>
    </div>
  </form>
</main>
{% endblock content %}

board/templates/board/review_confirm_delete.html
{% extends "board_base/base_with_navbar.html" %}

{% block title %}{{ review.title }} | MBCHATTING{% endblock title %}

{% block content %}
<main class="site-body">
  <form class="cp-dialog review-confirm-delete" method="post">
    {% csrf_token %}
    <span class="content">정말 리뷰를 삭제하시겠습니까?</span>
    <button class="cp-button warn" type="submit">삭제</button>
    <a class="cp-button secondary" href="{% url 'review-detail' review.id %}">취소</a>
  </form>
</main>
{% endblock content %}

board/templates/board/review_form.html
{% extends "board_base/base_with_navbar.html" %}

{% load widget_tweaks %}

{% block title %} 
  {% if review %}
    {{ review.title}}
  {% else %}
    새 포스트 작성
  {% endif %} 
{% endblock title %}

{% block content %}
<main class="site-body">
  <form class="review-form max-content-width" method="post" autocomplete="off" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="title">
      {{ form.title|add_class:"cp-input"|attr:"placeholder:제목"}}
      {% for error in form.title.errors %}
        <div class="error-message">{{ error }}</div>
      {% endfor %}
    </div>
    {% comment %} <div class="restaurant-name">
      {{ form.restaurant_name|add_class:"cp-input"|add_error_class:"error"|attr:"placeholder:음식점 이름"}}
      {% for error in form.restaurant_name.errors %}
        <div class="error-message">{{ error }}</div>
      {% endfor %}
    </div>
    <div class="restaurant-link">
      {{ form.restaurant_link|add_class:"cp-input"|add_error_class:"error"|attr:"placeholder:네이버 또는 카카오 플레이스 주소"}}
      {% for error in form.restaurant_link.errors %}
        <div class="error-message">{{ error }}</div>
      {% endfor %}

    </div>
    <div class="rating">
      <div class="cp-stars">
        {% for radio in form.rating %}
          {{radio}}
        {% endfor %}          
      </div>
      {% for error in form.rating.errors %}
      <div class="error-message">{{ error }}</div>
      {% endfor %}
    </div> {% endcomment %}
    <div class="content">
      {{ form.content|add_class:"cp-input"|add_error_class:"error"|attr:"placeholder:내용"}}
      {% for error in form.review.errors %}
        <div class="error-message">{{ error }}</div>
      {% endfor %}

    </div>
    <div class="file">
      <div class="file-content">
        {% if review.image1 %}
          <img src="{{ review.image1.url }}">
        {% endif %}
        <div>
          {{ form.image1 }}
          {% for error in form.image1.errors %}
            <div class="error-message">{{ error }}</div>
          {% endfor %}
        </div>
      </div>
    </div>
    <div class="file">
      <div class="file-content">
        {% if review.image2 %}
          <img src="{{ review.image2.url }}">
        {% endif %}
        <div>
          {{ form.image2 }}
          {% for error in form.image2.errors %}
          <div class="error-message">{{ error }}</div>
          {% endfor %}
        </div>
      </div>
    </div>
    <div class="file">
      <div class="file-content">
        {% if review.image3 %}
          <img src="{{ review.image3.url }}">
        {% endif %}
        <div>
          {{ form.image3 }}
          {% for error in form.image3.errors %}
          <div class="error-message">{{ error }}</div>
          {% endfor %}
        </div>
      </div>
    </div>

    <div class="buttons">
      <a 
        class="cp-button secondary cancel" 
        href="{% if review %}{% url 'review-detail' review.id %}{% else %}{% url 'index' %}{% endif %}"
      >
        취소
      </a>
      <button class="cp-button submit" type="submit">완료</button>
    </div>
  </form>
</main>
{% endblock content %}

board/templates/board/search_results.html
{% extends "board_base/base_with_navbar.html" %}

{% block title %}"{{ query }}" | MBCHATTING{% endblock title %}

{% block content %}
<main class="site-body">
  <div class="content-list max-content-width">
    <form class="search-form" action="{% url 'search' %}" method="get">
      <input class="search-input" name="query" value="{{ query }}" type="text" placeholder="게시글을 검색해보세요" required>
      <button class="cp-button search-button" type="submit">검색</button>
    </form>
    <div class="header">
      <h2>"{{ query }}"에 대한 겸색 결과 ({{ paginator.count }})</h2>
    </div>
    {% include 'components/review_list.html' with reviews=search_results empty_message="검색 결과가 없어요 :(" %}
    {% if is_paginated %}
      {% include 'components/pagination.html' with page_obj=page_obj %}
    {% endif %}
  </div>
</main>
{% endblock content %}